import './globals.css';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from './providers';
import MenuHamburguer from '@/components/MenuHamburguer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<NextAuthProvider>
					<nav className='flex justify-between fixed w-full bg-blend-saturation backdrop-filter backdrop-blur-sm items-center h-14 px-6 border-b border-gray-200 z-50'>
						<h1>Luisa Oliveira</h1>
						<MenuHamburguer />
					</nav>
					{children}
				</NextAuthProvider>
			</body>
		</html>
	);
}
